INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (1, 0, '신전 떡볶이');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (2, 0, '홍콩반점');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (3, 0, '안동찜닭');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (4, 0, '도스마스');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (5, 0, '맥도날드');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (6, 0, '롯데리아');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (7, 0, 'JUICY');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (8, 0, '할매 순대국');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (9, 0, '김밥천국');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (10, 0, '도스타코스');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (11, 0, '니뽕내뽕');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (12, 0, '도미노 피자');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (13, 0, '미스터 피자');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (14, 0, '피자헛');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (15, 0, '굽네 치킨');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (16, 0, '온누리 쭈꾸미');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (17, 0, '엉터리 생고기');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (18, 0, '삼목 등심');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (19, 0, '안동장');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (20, 0, '라이스&포테이토');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (21, 0, '동해해물칼국수');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (22, 0, '상도곱창');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (23, 0, '장독대');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (24, 0, '스시후');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (25, 0, '오시오 떡볶이');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (26, 0, '죠스 떡볶이');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (27, 0, '아딸');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (28, 0, '하노이의 별');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (29, 0, '준호네 돈가스');
INSERT INTO `interest` (`interest_id`, `category`, `name`) VALUES (30, 0, '곱창의 전설');



INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (1, 29, '4.jpg', '설향악', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (2, 43, '5.jpg', '진홍구', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (3, 23, '6.jpg', '신숭무', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (4, 48, '7.jpg', '구율봉', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (5, 29, '8.jpg', '고걸혜', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (6, 49, '9.jpg', '구가영', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (7, 30, '10.jpg', '전자건', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (8, 33, '11.jpg', '임채잎', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (9, 34, '12.jpg', '하다을', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (10, 37, '13.jpg', '서견명', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (11, 46, '14.jpg', '공상설', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (12, 33, '15.jpg', '추수손', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (13, 20, '16.jpg', '안향들', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (14, 48, '17.jpg', '오춘이', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (15, 11, '18.jpg', '임부두', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (16, 17, '19.jpg', '김건근', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (17, 28, '20.jpg', '강은술', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (18, 39, '21.jpg', '윤잔일', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (19, 30, '22.jpg', '설민운', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (20, 48, '23.jpg', '차분섭', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (21, 40, '24.jpg', '전비주', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (22, 29, '25.jpg', '오모조', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (23, 28, '26.jpg', '모견성', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (24, 20, '27.jpg', '전사광', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (25, 20, '28.jpg', '유아출', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (26, 27, '29.jpg', '공안욱', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (27, 23, '30.jpg', '남연손', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (28, 21, '31.jpg', '고윤이', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (29, 33, '32.jpg', '구승오', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (30, 34, '33.jpg', '엄현유', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (31, 24, '34.jpg', '심용슬', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (32, 19, '35.jpg', '신순하', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (33, 22, '36.jpg', '남흥나', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (34, 11, '37.jpg', '신황헌', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (35, 23, '0.jpg', '채순술', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (36, 10, '0.jpg', '전식율', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (37, 27, '0.jpg', '변가산', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (38, 30, '0.jpg', '조조영', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (39, 37, '0.jpg', '강만강', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (40, 31, '0.jpg', '남초석', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (41, 18, '0.jpg', '맹규은', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (42, 35, '0.jpg', '함림숙', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (43, 19, '0.jpg', '정운신', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (44, 15, '0.jpg', '조량전', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (45, 13, '0.jpg', '길황지', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (46, 21, '0.jpg', '소공항', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (47, 10, '0.jpg', '안무화', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (48, 32, '0.jpg', '왕람순', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (49, 34, '0.jpg', '전오회', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (50, 10, '0.jpg', '추얀곤', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (51, 34, '0.jpg', '임엽달', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (52, 22, '0.jpg', '변석묵', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (53, 10, '0.jpg', '석기익', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (54, 27, '0.jpg', '방늘동', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (55, 45, '0.jpg', '신판잔', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (56, 47, '0.jpg', '금량훔', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (57, 15, '0.jpg', '정묵봉', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (58, 11, '0.jpg', '양더향', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (59, 12, '0.jpg', '구반완', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (60, 22, '0.jpg', '석견랑', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (61, 11, '0.jpg', '기문마', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (62, 39, '0.jpg', '양휘권', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (63, 30, '0.jpg', '은규겸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (64, 10, '0.jpg', '구미식', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (65, 36, '0.jpg', '정신술', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (66, 12, '0.jpg', '소아철', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (67, 19, '0.jpg', '편범숭', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (68, 15, '0.jpg', '용중만', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (69, 20, '0.jpg', '권로익', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (70, 41, '0.jpg', '인공들', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (71, 36, '0.jpg', '노요걸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (72, 11, '0.jpg', '편휘웅', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (73, 35, '0.jpg', '신누람', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (74, 22, '0.jpg', '서용광', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (75, 13, '0.jpg', '마변나', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (76, 23, '0.jpg', '양월성', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (77, 25, '0.jpg', '방리철', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (78, 36, '0.jpg', '배애여', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (79, 17, '0.jpg', '육광상', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (80, 28, '0.jpg', '김변람', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (81, 32, '0.jpg', '최엽형', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (82, 12, '0.jpg', '장원섬', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (83, 38, '0.jpg', '제바성', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (84, 10, '0.jpg', '설실마', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (85, 34, '0.jpg', '선도개', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (86, 36, '0.jpg', '심림대', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (87, 13, '0.jpg', '한창부', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (88, 17, '0.jpg', '인주현', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (89, 38, '0.jpg', '정춘주', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (90, 30, '0.jpg', '윤주진', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (91, 11, '0.jpg', '공찬혜', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (92, 30, '0.jpg', '육견무', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (93, 45, '0.jpg', '천열호', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (94, 41, '0.jpg', '고향울', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (95, 27, '0.jpg', '배령견', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (96, 39, '0.jpg', '안달묵', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (97, 36, '0.jpg', '변애흔', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (98, 24, '0.jpg', '모화상', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (99, 38, '0.jpg', '양식솔', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (100, 13, '0.jpg', '방애요', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (101, 10, '0.jpg', '석문으', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (102, 28, '0.jpg', '설효경', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (103, 19, '0.jpg', '정로무', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (104, 44, '0.jpg', '위정묵', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (105, 21, '0.jpg', '노재예', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (106, 24, '0.jpg', '공걸련', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (107, 47, '0.jpg', '신규량', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (108, 38, '0.jpg', '함직슬', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (109, 19, '0.jpg', '노복택', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (110, 41, '0.jpg', '설려운', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (111, 27, '0.jpg', '허예분', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (112, 49, '0.jpg', '연섭묵', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (113, 47, '0.jpg', '옥옥하', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (114, 47, '0.jpg', '고혜잎', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (115, 28, '0.jpg', '백정윤', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (116, 49, '0.jpg', '변란익', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (117, 42, '0.jpg', '최보봉', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (118, 25, '0.jpg', '주비섬', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (119, 45, '0.jpg', '국마덕', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (120, 15, '0.jpg', '주단수', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (121, 35, '0.jpg', '김림성', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (122, 47, '0.jpg', '강길균', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (123, 12, '0.jpg', '마솔완', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (124, 44, '0.jpg', '지흔미', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (125, 24, '0.jpg', '구우부', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (126, 16, '0.jpg', '국창승', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (127, 17, '0.jpg', '홍희옥', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (128, 41, '0.jpg', '노관우', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (129, 45, '0.jpg', '제산준', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (130, 26, '0.jpg', '진리승', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (131, 27, '0.jpg', '천세려', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (132, 31, '0.jpg', '채원항', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (133, 14, '0.jpg', '성시아', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (134, 19, '0.jpg', '염누형', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (135, 23, '0.jpg', '반만운', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (136, 35, '0.jpg', '신울전', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (137, 38, '0.jpg', '송석디', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (138, 23, '0.jpg', '남노디', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (139, 19, '0.jpg', '정숭민', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (140, 37, '0.jpg', '진은용', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (141, 30, '0.jpg', '제로일', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (142, 29, '0.jpg', '위용모', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (143, 48, '0.jpg', '위광희', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (144, 46, '0.jpg', '노혁삼', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (145, 10, '0.jpg', '차들삼', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (146, 10, '0.jpg', '신혁견', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (147, 26, '0.jpg', '국경경', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (148, 14, '0.jpg', '손량걸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (149, 22, '0.jpg', '왕려지', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (150, 17, '0.jpg', '강솜철', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (151, 17, '0.jpg', '전잎대', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (152, 49, '0.jpg', '선도로', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (153, 21, '0.jpg', '민시잎', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (154, 47, '0.jpg', '전보마', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (155, 27, '0.jpg', '방부뜸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (156, 18, '0.jpg', '황소배', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (157, 40, '0.jpg', '백규빈', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (158, 17, '0.jpg', '방두선', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (159, 45, '0.jpg', '반택손', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (160, 31, '0.jpg', '신숭근', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (161, 21, '0.jpg', '최태백', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (162, 27, '0.jpg', '은길사', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (163, 21, '0.jpg', '나훔명', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (164, 10, '0.jpg', '위려현', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (165, 10, '0.jpg', '강빛백', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (166, 33, '0.jpg', '김전인', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (167, 27, '0.jpg', '진덕새', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (168, 25, '0.jpg', '나엄래', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (169, 18, '0.jpg', '하회인', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (170, 21, '0.jpg', '연송환', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (171, 20, '0.jpg', '방우휴', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (172, 34, '0.jpg', '진욱다', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (173, 14, '0.jpg', '남련새', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (174, 24, '0.jpg', '함제진', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (175, 22, '0.jpg', '엄지추', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (176, 25, '0.jpg', '한도욱', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (177, 40, '0.jpg', '심종초', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (178, 42, '0.jpg', '최운곤', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (179, 16, '0.jpg', '황관월', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (180, 19, '0.jpg', '허정사', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (181, 13, '0.jpg', '최종훔', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (182, 44, '0.jpg', '엄향술', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (183, 29, '0.jpg', '성예린', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (184, 40, '0.jpg', '국중섭', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (185, 24, '0.jpg', '옥은면', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (186, 38, '0.jpg', '방직사', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (187, 12, '0.jpg', '전령욱', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (188, 33, '0.jpg', '유황개', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (189, 10, '0.jpg', '길빈해', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (190, 11, '0.jpg', '엄조주', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (191, 48, '0.jpg', '편시준', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (192, 16, '0.jpg', '문운혼', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (193, 26, '0.jpg', '석예슬', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (194, 22, '0.jpg', '오면경', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (195, 45, '0.jpg', '은이민', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (196, 25, '0.jpg', '윤홍항', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (197, 17, '0.jpg', '육월남', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (198, 33, '0.jpg', '류강다', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (199, 22, '0.jpg', '제고건', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (200, 23, '0.jpg', '허길혁', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (201, 36, '0.jpg', '진걸삼', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (202, 41, '0.jpg', '신혁곤', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (203, 48, '0.jpg', '방규겸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (204, 20, '0.jpg', '여형라', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (205, 34, '0.jpg', '모강성', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (206, 43, '0.jpg', '유여인', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (207, 44, '0.jpg', '양술백', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (208, 44, '0.jpg', '추리천', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (209, 15, '0.jpg', '모기량', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (210, 13, '0.jpg', '오래이', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (211, 16, '0.jpg', '현휘형', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (212, 44, '0.jpg', '서로엄', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (213, 26, '0.jpg', '정루곤', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (214, 27, '0.jpg', '신형엽', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (215, 41, '0.jpg', '제빛판', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (216, 21, '0.jpg', '반들직', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (217, 42, '0.jpg', '임호혜', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (218, 15, '0.jpg', '주기면', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (219, 24, '0.jpg', '강회위', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (220, 36, '0.jpg', '공광화', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (221, 19, '0.jpg', '양도가', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (222, 40, '5.jpg', '권창남', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (223, 29, '0.jpg', '변초래', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (224, 33, '0.jpg', '선혼운', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (225, 44, '0.jpg', '제월웅', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (226, 40, '3.jpg', '추은문', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (227, 17, '0.jpg', '차비후', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (228, 24, '0.jpg', '배면주', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (229, 23, '0.jpg', '제람위', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (230, 23, '0.jpg', '채언미', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (231, 10, '0.jpg', '변광성', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (232, 17, '0.jpg', '양중분', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (233, 21, '0.jpg', '임삼대', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (234, 22, '0.jpg', '주명훔', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (235, 25, '0.jpg', '강인뜸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (236, 28, '0.jpg', '임술개', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (237, 46, '0.jpg', '민다림', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (238, 30, '0.jpg', '김천묵', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (239, 17, '0.jpg', '우길진', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (240, 14, '0.jpg', '오휘문', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (241, 41, '0.jpg', '길반걸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (242, 15, '0.jpg', '방새빈', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (243, 28, '0.jpg', '기직종', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (244, 34, '0.jpg', '장란린', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (245, 21, '0.jpg', '제도모', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (246, 33, '0.jpg', '금란박', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (247, 41, '0.jpg', '장휘만', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (248, 25, '0.jpg', '선형실', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (249, 43, '0.jpg', '곽병한', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (250, 12, '0.jpg', '황익로', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (251, 44, '0.jpg', '채송희', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (252, 33, '0.jpg', '인송헌', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (253, 39, '0.jpg', '임석기', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (254, 43, '0.jpg', '탁량일', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (255, 11, '0.jpg', '강신환', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (256, 45, '0.jpg', '민요면', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (257, 48, '0.jpg', '권학제', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (258, 38, '0.jpg', '고옥치', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (259, 30, '0.jpg', '임삼소', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (260, 20, '0.jpg', '진평개', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (261, 47, '0.jpg', '우용배', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (262, 18, '0.jpg', '박이여', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (263, 17, '0.jpg', '안수량', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (264, 19, '0.jpg', '원치인', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (265, 18, '0.jpg', '노삼혁', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (266, 30, '0.jpg', '금가손', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (267, 17, '0.jpg', '추늘울', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (268, 45, '0.jpg', '서충모', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (269, 28, '0.jpg', '제덕나', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (270, 33, '0.jpg', '맹형신', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (271, 10, '0.jpg', '금승량', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (272, 44, '0.jpg', '정반뜸', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (273, 39, '0.jpg', '윤두옥', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (274, 19, '0.jpg', '모산일', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (275, 39, '0.jpg', '방단미', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (276, 20, '0.jpg', '금강달', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (277, 12, '0.jpg', '강희익', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (278, 15, '0.jpg', '조복라', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (279, 17, '0.jpg', '마화기', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (280, 22, '0.jpg', '연준신', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (281, 30, '0.jpg', '명충예', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (282, 46, '0.jpg', '방늘승', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (283, 40, '0.jpg', '정두구', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (284, 45, '0.jpg', '송분사', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (285, 14, '0.jpg', '현악고', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (286, 37, '0.jpg', '방언빛', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (287, 28, '0.jpg', '양현숙', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (288, 41, '0.jpg', '양관숙', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (289, 38, '0.jpg', '기황대', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (290, 13, '0.jpg', '원권온', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (291, 43, '0.jpg', '현치리', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (292, 16, '0.jpg', '금엄치', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (293, 45, '0.jpg', '최얀보', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (294, 36, '0.jpg', '차술별', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (295, 30, '0.jpg', '유마엽', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (296, 17, '0.jpg', '양종잎', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (297, 41, '0.jpg', '송춘규', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (298, 13, '0.jpg', '도얀환', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (299, 23, '0.jpg', '함명가', NULL);
INSERT INTO `person` (`person_id`, `age`, `image_url`, `name`, `job_id`) VALUES  (300, 21, '0.jpg', '한충식', NULL);

INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('1', '1');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('2', '1');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('3', '1');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('2', '2');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('3', '2');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('4', '2');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('1', '3');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('2', '3');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('5', '3');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('1', '4');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('2', '5');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('1', '6');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('1', '7');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('2', '8');
INSERT INTO `person_interest` (`interest_interest_id`, `person_person_id`) VALUES ('3', '8');

INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('2', '1');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('1', '2');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('3', '1');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('1', '3');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('2', '3');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('2', '2');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('3', '5');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('5', '3');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('7', '1');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('1', '7');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('2', '9');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('9', '2');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('4', '8');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('8', '4');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('11', '1');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('1', '11');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('7', '13');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('13', '7');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('5', '8');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('8', '5');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('3', '22');
INSERT INTO `friend_relation` (`friend_id`, `owner_id`) VALUES ('22', '3');